name: anisoML
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python >=3.10
  - flowermd
  - numpy
  - pytorch=2.0.1
  - pytorch-cuda=11.7
  - pytorch3d
  - signac=1.7.0
  - signac-flow=0.18.1
  - pandas
  - matplotlib
  - wandb
  - jupyter
