name: anisohuang
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
<<<<<<< Updated upstream
  - pytorch=2.2.1
  - pytorch-cuda=11.8
=======
  - pytorch
  - flowermd
>>>>>>> Stashed changes
  - numpy
  - rowan
  - signac=1.7.0
  - signac-flow=0.18.1
  - pandas
  - matplotlib
  - wandb
  - jupyter
