name: anisoML
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - pytorch
  - pytorch-cuda=11.7
  - flowermd
  - numpy
  - rowan
  - pytorch3d
  - signac=1.7.0
  - signac-flow=0.18.1
  - pandas
  - matplotlib
  - wandb
  - jupyter
