wandb_version: 1

overfit:
  desc: null
  value: false
batch_size:
  desc: null
  value: 2
shrink:
  desc: null
  value: false
lr:
  desc: null
  value: 0.001
in_dim:
  desc: null
  value: 92
hidden_dim:
  desc: null
  value: 10
n_layer:
  desc: null
  value: 2
optim:
  desc: null
  value: Adam
decay:
  desc: null
  value: 0.001
act_fn:
  desc: null
  value: Tanh
dropout:
  desc: null
  value: 0.3
use_scheduler:
  desc: null
  value: false
scheduler_type:
  desc: null
  value: StepLR
loss_type:
  desc: null
  value: mse
batch_norm:
  desc: null
  value: false
resume:
  desc: null
  value: false
prior_energy:
  desc: null
  value: true
prior_energy_sigma:
  desc: null
  value: 1
prior_energy_n:
  desc: null
  value: 6
_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1704394785.344224
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 1
      - 15
      - 16
      - 23
      4: 3.11.7
      5: 0.16.1
      8:
      - 5
      13: linux-x86_64
